version: '3'

services:
  mysql:
    image: mysql:8.0.33
    # restart: always
    container_name: learn_springboot_mysql8
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3309:3306
    volumes:
      - ./dockerDB/mysql:/var/lib/docker/volumes/mysql_data
  redis:
    image: redis:latest
    # restart: always
    container_name: learn_springboot_redis
    command:
      --requirepass "root" #这一行是设置密码
    ports:
      - 3310:6379
    volumes:
      - ./dockerDB/redis:/var/lib/docker/volumes/redis_data
    privileged: true      #使用该参数，container内的root拥有真正的root权限