server:
    port: 2546

spring:
    datasource:
        url: jdbc:mysql://localhost:3309/coffee?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
        username: root
        password: 2546
        driver-class-name: com.mysql.cj.jdbc.Driver