server:
    # 服务端口
    port: 2546

spring:
    datasource:
        url: jdbc:mysql://localhost:3309/coffee?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 2546
        driver-class-name: com.mysql.cj.jdbc.Driver
       # HikariCP 自定义连接池配置
        hikari:
            minimum-idle: 10 # 池中维护的最小空闲连接数，默认为 10 个。
            maximum-pool-size: 20 # 池中最大连接数，包括闲置和使用中的连接，默认为 10 个。
    jpa:
        # 执行数据库操作时显示执行的sql
        show-sql: true
        hibernate:
            # create:启动时删除原表 后创建表 结束后不操作
            # create-drop:启动时删除原表 后创建表 结束后删除表 如果表不存在会报错
            # update:启动时自动更新表字段结构 原有数据保留
            # validate:启动时校验表字段结构 如果不一致则报错
            ddl-auto: create
        # 设置默认view为false消除警告
        open-in-view: false
    mvc:
        # swaggerAPI配置 
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
    redis:
        # Redis数据库索引(默认为0)
        database: 0
        # Redis服务器地址
        host: localhost
        # Redis服务器连接端口
        port: 3310
        # Redis服务器连接密码(默认为空)
        password: 2546
        # 连接超时时间 (毫秒)
        timeout: 5000ms
        lettuce:
            pool:
                # 连接池最大连接数(使用负值表示没有限制) 默认 8
                max-active: 8
                # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认 -1
                max-wait: -1
                # 连接池中的最大空闲连接 默认 8
                max-idle: 8
                # 连接池中的最小空闲连接 默认 0
                min-idle: 0